### ISSUE TITLE
Can human images be reconstructed?

### ISSUE THREAD

**Issue by MritulaC** [krtin/3dreconstruction#1]
Hi,
 Just want to check if human 2D images  can be reconstructed to 3D images?

Thanks,
 Mritula

**Comment by aakashnandi198** [comment]
Hi,

Technically yes , you should be able to reconstructed any 3d object from 2d images, however:-

1) a dense reconstruction would only take place where good stereo matching takes place which depends on number of matching points across a pair of images. So if you have an object that is completely made of a single colour and lacks variation in intensity then this would fail.

2) This code is not the state of the art method of 3d reconstruction from multiple 2d images as it does not perform bundle adjustment but only image - pair wise matching in a sequential fashion as a result the 3d reconstruction is skewed.

3) I would suggest you rely on "[Building rome in a day](https://grail.cs.washington.edu/rome/)" paper if you are to get a good idea on this topic. Also have a look at matlab's 3d reconstruction inbuilt function .


Thanks,
Aakash
